// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfoxp3Mq2ptLxQixbr43OfT8N_tv5ifh4',
    appId: '1:113712759961:web:de7026fb58a42a52f4a408',
    messagingSenderId: '113712759961',
    projectId: 'expenses-tracker-2025-470de',
    authDomain: 'expenses-tracker-2025-470de.firebaseapp.com',
    storageBucket: 'expenses-tracker-2025-470de.firebasestorage.app',
    measurementId: 'G-97S25SS5EW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBccDcjxGB2fN-FhQH1fg0gN8upkZPKj08',
    appId: '1:113712759961:android:6b5957e061f60095f4a408',
    messagingSenderId: '113712759961',
    projectId: 'expenses-tracker-2025-470de',
    storageBucket: 'expenses-tracker-2025-470de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXIhX449LE_ameeQFy8cA9TP1d6EV6xPk',
    appId: '1:113712759961:ios:ceedb367204a2224f4a408',
    messagingSenderId: '113712759961',
    projectId: 'expenses-tracker-2025-470de',
    storageBucket: 'expenses-tracker-2025-470de.firebasestorage.app',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXIhX449LE_ameeQFy8cA9TP1d6EV6xPk',
    appId: '1:113712759961:ios:ceedb367204a2224f4a408',
    messagingSenderId: '113712759961',
    projectId: 'expenses-tracker-2025-470de',
    storageBucket: 'expenses-tracker-2025-470de.firebasestorage.app',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfoxp3Mq2ptLxQixbr43OfT8N_tv5ifh4',
    appId: '1:113712759961:web:9cd926fbfaca9d43f4a408',
    messagingSenderId: '113712759961',
    projectId: 'expenses-tracker-2025-470de',
    authDomain: 'expenses-tracker-2025-470de.firebaseapp.com',
    storageBucket: 'expenses-tracker-2025-470de.firebasestorage.app',
    measurementId: 'G-RJJYG0DXSQ',
  );
}
